# Generated by Django 5.2.7 on 2025-10-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_id_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Electrónica'), (2, 'Ropa'), (3, 'Alacena'), (4, 'Refrigerados'), (5, 'Higiene, salud, y belleza'), (6, 'Hogar'), (7, 'Deportes'), (8, 'Otros')], null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_anadido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_id',
            field=models.IntegerField(blank=True, choices=[(1020, '1020- Carnes Y Productos de Origen Animal'), (2030, '2030- Lacteos y Derivados'), (3040, '3040- Electronica y Accesorios'), (4050, '4050- Ropa y Calzado'), (5060, '5060- Articulos de Hogar'), (6070, '6070- Articulos de Deporte'), (7080, '7080- Suministros de Higiene y Belleza'), (8090, '8090- Productos Varios')], null=True),
        ),
    ]
